### ISSUE TITLE
Error during SSL certificate renewal

### ISSUE THREAD

**Issue by Rapha-Borges** [Rapha-Borges/deploy-vaultwarden#2]
I identified a misconfiguration preventing the automatic renewal of the SSL certificate. To resolve this, it was necessary to change the port configurations for both the NGINX Proxy Manager and Vaultwarden.

Vaultwarden's port was changed from `80` to `8081`.
NGINX Proxy Manager port was changed from `8080` to `80`.

To apply the configuration, the containers need to be restarted with the new settings, and the port on which Vaultwarden is listening should be updated within the Nginx Proxy Manager, as shown in the image below:

![nginx-proxy-1](https://github.com/user-attachments/assets/224dd151-f479-4f00-8c8c-a611b4d78c8b)

**Comment by displaynone** [comment]
Thanks for sharing the fix

**Comment by Rapha-Borges** [comment]
You're welcome, and thank you for your feedback on Twitter (X). It's great to know that others are able to replicate the tutorial.

PS: The docker compose file in the repository has already been updated, as well as the image with the port change in Nginx.
