### ISSUE TITLE
SSL creation giving me error

### ISSUE THREAD

**Issue by Nightwalker83** [Rapha-Borges/deploy-vaultwarden#5]
Hi,

During step 3 in the Lets encrypt setup for the ssl

https://github.com/Rapha-Borges/deploy-vaultwarden

The form an error "internal error" message when submitted.

The details of 

Domain: Vaultwarden
Scheme: http
IP:172.18.0.3 (docker container)

**Comment by Rapha-Borges** [comment]
Hey there, sorry to hear you're running into this.

I'm a bit confused about what's going on. Can you give me more info?

Step 3 is just about making a TOKEN that you'll use to log into Vaultwarden later. It should be like this photo:

![image](https://github.com/user-attachments/assets/d4117675-e4a2-498f-a15e-f7f14c31d586)

Thank you for helping me improve the project by reporting this issue. I hope I can help you whit this problem.

**Comment by Nightwalker83** [comment]
I mean the proxy manager setup sorry!

**Comment by Rapha-Borges** [comment]
Hey there, 

There's not enough information for me to help you yet. Can you provide some more details?

- Are you using a valid domain?

- Could you run the command `docker compose logs -f` in the directory where your `docker-compose.yaml` file is located and try the procedure again? After that, please paste the error that appears from the `nginx-proxy-1` container here.

**Comment by Nightwalker83** [comment]
Well, it fails regardless of what I put for a domain such as vaultwarden.localhost or vaultwarden.ddns.net and when I check the logs they are empty.

**Comment by Nightwalker83** [comment]
I managed to get it to work by uploading certs created outside of letsencrypt.

**Comment by Rapha-Borges** [comment]
Yes, since you're not using a valid domain/IP, the Certbot in Nginx Proxy Manager can't generate the certificate. I think that's the only way it would work. Glad to hear it worked out!
